name: cybersecagentsuite
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/cybersecagentsuite
  original_url: https://huggingface.co/spaces/Chris4K/cybersecagentsuite

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 12:59:58
